# Generated by Django 4.2.7 on 2023-12-16 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_model', '0004_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_model.car_model')),
            ],
        ),
    ]
