# Generated by Django 4.2.7 on 2024-01-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buy_car_created_on'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buy_car',
        ),
    ]
