# Generated by Django 4.2.7 on 2023-12-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car_model',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='car_price',
            field=models.CharField(max_length=40),
        ),
    ]
