# Generated by Django 4.2.7 on 2023-12-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0002_car_model_quantity_alter_car_model_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_model/media/uploads/'),
        ),
    ]
